aminvakil/aur

- gnome-shell-extension-workspace-matrix/.SRCINFO
- gnome-shell-extension-workspace-matrix/PKGBUILD
> upgpkg: gnome-shell-extension-workspace-matrix 5.0.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 19.0.0-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.0.4-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 19.1.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 19.2.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 19.2.1-1

- ansible-lint-git/.SRCINFO
- ansible-lint-git/PKGBUILD
https://github.com/archlinux/svntogit-community/commit/cb42e1915a0924b3eae3a4fa9a34604704cc3e6b
also change ansible to ansible-community in source
> change python-setuptools_scm makedepend to python-setuptools-scm

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 19.2.2-1

- butane-bin/.SRCINFO
- butane-bin/PKGBUILD
- butane/.SRCINFO
- butane/PKGBUILD
> upgpkg: butane 0.13.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 19.3.0-1

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.3-1

- dockle/.SRCINFO
- dockle/PKGBUILD
> upgpkg: dockle 0.4.2-1

- gnome-shell-extension-workspace-matrix/.SRCINFO
- gnome-shell-extension-workspace-matrix/PKGBUILD
> upgpkg: gnome-shell-extension-workspace-matrix 6.1-1

- gnome-shell-extension-workspace-matrix/.SRCINFO
- gnome-shell-extension-workspace-matrix/PKGBUILD
Fix missing directories from installation
> upgpkg: gnome-shell-extension-workspace-matrix 6.1-2

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 19.4.0-1

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.7-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.0.6-1

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.8-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.6.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 19.5.0-1

- ansible-lint-git/.SRCINFO
- ansible-lint-git/PKGBUILD
https://github.com/ansible-community/ansible-lint/commit/3e28f9f
> upgpkg: ansible-lint-git 5.2.1.r10.g15565da-1

- ci/pumba/before_makepkg.sh
- pumba-bin/.SRCINFO
- pumba-bin/PKGBUILD
- pumba/.SRCINFO
- pumba/PKGBUILD
> upgpkg: pumba 0.9.0-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.0.7-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.0.9-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.6.1-1

- gnome-shell-extension-workspace-matrix/.SRCINFO
- gnome-shell-extension-workspace-matrix/PKGBUILD
> upgpkg: gnome-shell-extension-workspace-matrix 6.3-1

- jmeter-plugins-manager/.SRCINFO
- jmeter-plugins-manager/PKGBUILD
> upgpkg: jmeter-plugins-manager 1.7-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.7.0-1

- gnome-shell-extension-workspace-matrix/.SRCINFO
- gnome-shell-extension-workspace-matrix/PKGBUILD
> upgpkg: gnome-shell-extension-workspace-matrix 6.4-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.7.2-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 19.5.1-1

- python-spotdl/.SRCINFO
- python-spotdl/PKGBUILD
> upgpkg: python-spotdl 3.9.3-1

- ci/hadolint-git/before_makepkg.sh
Enable `testing` and `community-testing` repositories
> hadolint-git testing repositories

- ansible-lint-git/.SRCINFO
- ansible-lint-git/PKGBUILD
https://github.com/ansible-community/ansible-lint/commit/18cf50
> Change license installation

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.7.3-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 20.0.0-1

- dockle/.SRCINFO
- dockle/PKGBUILD
> upgpkg: dockle 0.4.4-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.7.4-1

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.9-1

- .github/workflows/ci.yml
- .github/workflows/schedule.yml
It gets run by default, but I'd like to add it to be explicit.
> Add --check to makepkg command

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.7.5-1

- ansible-lint-git/.SRCINFO
- ansible-lint-git/PKGBUILD
https://github.com/ansible-community/ansible-lint/commit/2848616
https://github.com/ansible-community/ansible-lint/pull/1906
> Remove python-tenacity from deps

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 20.0.1-1

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.10-1

- docker-bench-security/.SRCINFO
- docker-bench-security/PKGBUILD
> upgpkg: docker-bench-security 1.3.6-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 20.1.0-1

- python-spotdl/.SRCINFO
- python-spotdl/PKGBUILD
> upgpkg: python-spotdl 3.9.4-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.7.6-1

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.11-1

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.12-1

- python-spotdl/.SRCINFO
- python-spotdl/PKGBUILD
> upgpkg: python-spotdl 3.9.5-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 21.0.0-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.7.9-1

- gnome-shell-extension-workspace-matrix/.SRCINFO
- gnome-shell-extension-workspace-matrix/PKGBUILD
> upgpkg: gnome-shell-extension-workspace-matrix 7.0-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.0.10-1

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.13-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.0.11-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 21.1.0-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.8.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 21.2.0-1

- ci/hadolint-git/before_makepkg.sh
Set locale before_makepkg hadolint-git
> Set locale before_makepkg hadolint-git

- ci/hadolint-git/before_makepkg.sh
This reverts commit fc4b2b1b484d3b64d05ed19140c78f1ca4ac5c79, reversing
changes made to d7c80b10549c6e88992ffa5bda368b6d255174c4.
> Revert "Merge pull request #147 from aminvakil/hadolint_git_en_US"

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.14-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.8.1-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 21.3.0-1

- dockle/.SRCINFO
- dockle/PKGBUILD
> upgpkg: dockle 0.4.6-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.0.13-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 21.4.0-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.0.14-1

- ansible-lint-git/.SRCINFO
- ansible-lint-git/PKGBUILD
Add python-filelock to depends
> ansible-lint-git: Add python-filelock to depends

- gnome-shell-extension-workspace-matrix/.SRCINFO
- gnome-shell-extension-workspace-matrix/PKGBUILD
> upgpkg: gnome-shell-extension-workspace-matrix 7.1-1

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.16-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 21.5.0-1

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.17-1

- ci/python-spotdl/before_makepkg.sh
Remove unnecessary aur packages
> python-spotdl: Remove unnecessary aur packages

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.8.2-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.8.3-1

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.18-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 21.6.0-1

- gnome-shell-extension-workspace-matrix/.SRCINFO
- gnome-shell-extension-workspace-matrix/PKGBUILD
> upgpkg: gnome-shell-extension-workspace-matrix 7.2-1

- ci/ansible-lint-git/after_makepkg.sh
- Also test ansible-role-node-exporter in ansible-lint
- Trigger ansible-lint-git CI
> ansible lint add role

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.19-1

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.20-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 21.7.0-1

- dockle/.SRCINFO
- dockle/PKGBUILD
> upgpkg: dockle 0.4.7-1

- butane/.SRCINFO
- butane/PKGBUILD
> upgpkg: butane 0.16.0-1

- butane-bin/.SRCINFO
- butane-bin/PKGBUILD
> upgpkg: butane-bin 0.16.0-1

- dockle/.SRCINFO
- dockle/PKGBUILD
> upgpkg: dockle 0.4.8-1

- ci/python-spotdl/after_makepkg.sh
- python-spotdl/.SRCINFO
- python-spotdl/PKGBUILD
> upgpkg: python-spotdl 4.0.0-1

- dockle/.SRCINFO
- dockle/PKGBUILD
> upgpkg: dockle 0.4.9-1

- python-spotdl/.SRCINFO
- python-spotdl/PKGBUILD
> upgpkg: python-spotdl 4.0.1-1

- jmeter-plugins-manager/.SRCINFO
- jmeter-plugins-manager/PKGBUILD
> upgpkg: jmeter-plugins-manager 1.8-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 21.8.0-1

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.22-1

- python-spotdl/.SRCINFO
- python-spotdl/PKGBUILD
> upgpkg: python-spotdl 4.0.2-1

- python-spotdl/.SRCINFO
- python-spotdl/PKGBUILD
> upgpkg: python-spotdl 4.0.3-1

- python-spotdl/.SRCINFO
- python-spotdl/PKGBUILD
> upgpkg: python-spotdl 4.0.5-1

- hadolint-git/.SRCINFO
- hadolint-git/PKGBUILD
- hadolint-git/stack.yaml
Thanks to @m-pilia as this is shamelessly copied from https://aur.archlinux.org/cgit/aur.git/commit/?h=hadolint&id=96c8690
> Use custom stack.yaml

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 21.9.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 21.10.0-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.9.1-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 21.10.1-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.10.0-1

- ci/hadolint-git/before_makepkg.sh
- hadolint-git/.SRCINFO
- hadolint-git/PKGBUILD
- Disable hadolint_git testing repository
- upgpkg: hadolint-git 2.12.1.beta.r7.g7c54238-1
> hadolint git disable testing

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 21.10.2-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.11.0-1

- gnome-shell-extension-workspace-matrix/.SRCINFO
- gnome-shell-extension-workspace-matrix/PKGBUILD
> upgpkg: gnome-shell-extension-workspace-matrix 7.3-1

- butane/.SRCINFO
- butane/PKGBUILD
> upgpkg: butane 0.17.0-1

- python-spotdl/.SRCINFO
- python-spotdl/PKGBUILD
> upgpkg: python-spotdl 4.0.7-1

- pumba-bin/.SRCINFO
- pumba-bin/PKGBUILD
> upgpkg: pumba-bin 0.9.7-1

- pumba/.SRCINFO
- pumba/PKGBUILD
> upgpkg: pumba 0.9.7-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.12.0-1

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.23-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 21.11.0-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.13.0-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.13.1-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.13.2-1

- dockle/.SRCINFO
- dockle/PKGBUILD
> upgpkg: dockle 0.4.11-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 21.12.0-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.14.0-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.14.1-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.15.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 21.13.0-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.15.1-1

- docker-bench-security/.SRCINFO
- docker-bench-security/PKGBUILD
> upgpkg: docker-bench-security 1.5.0-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.15.3-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.15.4-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 21.14.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 22.0.0-1

- butane-bin/.SRCINFO
- butane-bin/PKGBUILD
> upgpkg: butane-bin 0.18.0-1

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.24-1

- python-spotdl/.SRCINFO
- python-spotdl/PKGBUILD
> upgpkg: python-spotdl 4.1.4-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.16.1-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.16.2-1

- gnome-shell-extension-workspace-matrix/.SRCINFO
- gnome-shell-extension-workspace-matrix/PKGBUILD
> upgpkg: gnome-shell-extension-workspace-matrix 8.0-1

- python-spotdl/.SRCINFO
- python-spotdl/PKGBUILD
> upgpkg: python-spotdl 4.1.6-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.16.6-1

- python-spotdl/.SRCINFO
- python-spotdl/PKGBUILD
> upgpkg: python-spotdl 4.1.8-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 0.16.7-1

- python-spotdl/.SRCINFO
- python-spotdl/PKGBUILD
> upgpkg: python-spotdl 4.1.10-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.0.16-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 1.0.0-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 1.0.1-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 22.3.0-1

- python-spotdl/.SRCINFO
- python-spotdl/PKGBUILD
> upgpkg: python-spotdl 4.1.11-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 1.0.3-1

- jmeter-plugins-manager/.SRCINFO
- jmeter-plugins-manager/PKGBUILD
> upgpkg: jmeter-plugins-manager 1.9-1

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.25-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 22.4.0-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 1.0.4-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.0.17-1

- dockle/.SRCINFO
- dockle/PKGBUILD
> upgpkg: dockle 0.4.13-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 22.5.0-1

- dstp/.SRCINFO
- dstp/PKGBUILD
> upgpkg: dstp 0.4.0-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.0.18-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 22.6.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 22.7.0-1

- docker-bench-security/.SRCINFO
- docker-bench-security/PKGBUILD
> upgpkg: docker-bench-security 1.6.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 23.0.0-1

- pumba-bin/.SRCINFO
- pumba-bin/PKGBUILD
> upgpkg: pumba-bin 0.10.1-1

- pumba/.SRCINFO
- pumba/PKGBUILD
> upgpkg: pumba 0.10.1-1

- actionlint/.SRCINFO
- actionlint/PKGBUILD
> upgpkg: actionlint 1.6.26-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 23.2.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 23.3.0-1

- butane/.SRCINFO
- butane/PKGBUILD
> upgpkg: butane 0.19.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 23.3.1-1

- gnome-shell-extension-workspace-matrix/.SRCINFO
- gnome-shell-extension-workspace-matrix/PKGBUILD
> upgpkg: gnome-shell-extension-workspace-matrix 9.0-1

- jmeter-plugins-manager/.SRCINFO
- jmeter-plugins-manager/PKGBUILD
> upgpkg: jmeter-plugins-manager 1.10-1

- gnome-shell-extension-workspace-matrix/.SRCINFO
- gnome-shell-extension-workspace-matrix/PKGBUILD
> upgpkg: gnome-shell-extension-workspace-matrix 9.1-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 23.4.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 23.5.0-1

- ddosify/.SRCINFO
- ddosify/PKGBUILD
> upgpkg: ddosify 1.0.6-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 23.5.1-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.0.20-1

- docker-bench-security/.SRCINFO
- docker-bench-security/PKGBUILD
> upgpkg: docker-bench-security 1.6.1-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.0.21-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 23.6.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 23.7.0-1

- dockle/.SRCINFO
- dockle/PKGBUILD
> upgpkg: dockle 0.4.14-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 23.8.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 23.8.1-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 23.9.0-1

- butane/.SRCINFO
- butane/PKGBUILD
> upgpkg: butane 0.20.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 24.0.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 24.1.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 24.2.0-1

- gnome-shell-extension-workspace-matrix/.SRCINFO
- gnome-shell-extension-workspace-matrix/PKGBUILD
> upgpkg: gnome-shell-extension-workspace-matrix 10.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 24.3.0-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.0.22-1

- anteon/.SRCINFO
- anteon/PKGBUILD
> upgpkg: anteon 1.7.2-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 24.4.0-1

- anteon/.SRCINFO
- anteon/PKGBUILD
> upgpkg: anteon 2.2.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 24.5.0-1

- butane/.SRCINFO
- butane/PKGBUILD
> upgpkg: butane 0.21.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 24.6.0-1

- awx/.SRCINFO
- awx/PKGBUILD
> upgpkg: awx 24.6.1-1

- anteon/.SRCINFO
- anteon/PKGBUILD
> upgpkg: anteon 2.5.0-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.0.23-1

- anteon/.SRCINFO
- anteon/PKGBUILD
> upgpkg: anteon 2.6.0-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.0.24-1

- spotdl/.SRCINFO
- spotdl/PKGBUILD
> upgpkg: spotdl 4.2.7-1

- spotdl/.SRCINFO
- spotdl/PKGBUILD
> upgpkg: spotdl 4.2.8-1

- butane/.SRCINFO
- butane/PKGBUILD
> upgpkg: butane 0.22.0-1

- butane-bin/.SRCINFO
- butane-bin/PKGBUILD
> upgpkg: butane-bin 0.22.0-1

- gnome-shell-extension-workspace-matrix/.SRCINFO
- gnome-shell-extension-workspace-matrix/PKGBUILD
> upgpkg: gnome-shell-extension-workspace-matrix 11.0-1

- gnome-shell-extension-workspace-matrix/.SRCINFO
- gnome-shell-extension-workspace-matrix/PKGBUILD
> upgpkg: gnome-shell-extension-workspace-matrix 11.1-1

- spotdl/.SRCINFO
- spotdl/PKGBUILD
> upgpkg: spotdl 4.2.9-1

- spotdl/.SRCINFO
- spotdl/PKGBUILD
> upgpkg: spotdl 4.2.10-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.0.25-1

- cadvisor-bin/.SRCINFO
- cadvisor-bin/PKGBUILD
> upgpkg: cadvisor-bin 0.49.2-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.0.26-1

- butane/.SRCINFO
- butane/PKGBUILD
> upgpkg: butane 0.23.0-1

- butane-bin/.SRCINFO
- butane-bin/PKGBUILD
> upgpkg: butane-bin 0.23.0-1

- dockle/.SRCINFO
- dockle/PKGBUILD
> upgpkg: dockle 0.4.15-1

- dstp/.SRCINFO
- dstp/PKGBUILD
> upgpkg: dstp 0.4.23-1

- spotdl/.SRCINFO
- spotdl/PKGBUILD
> upgpkg: spotdl 4.2.11-1

- android-sdk-build-tools/.SRCINFO
- android-sdk-build-tools/PKGBUILD
> upgpkg: android-sdk-build-tools r35.0.1-1

- gnome-shell-extension-workspace-matrix/.SRCINFO
- gnome-shell-extension-workspace-matrix/PKGBUILD
> upgpkg: gnome-shell-extension-workspace-matrix 11.3-1

- pumba-bin/.SRCINFO
- pumba-bin/PKGBUILD
> upgpkg: pumba-bin 0.11.1-1

- pumba/.SRCINFO
- pumba/PKGBUILD
> upgpkg: pumba 0.11.1-1

- pumba-bin/.SRCINFO
- pumba-bin/PKGBUILD
> upgpkg: pumba-bin 0.11.5-1

- pumba/.SRCINFO
- pumba/PKGBUILD
> upgpkg: pumba 0.11.5-1

- gnome-shell-extension-workspace-matrix/.SRCINFO
- gnome-shell-extension-workspace-matrix/PKGBUILD
> upgpkg: gnome-shell-extension-workspace-matrix 12.0-1

- pumba-bin/.SRCINFO
- pumba-bin/PKGBUILD
> upgpkg: pumba-bin 0.11.6-1

- pumba/.SRCINFO
- pumba/PKGBUILD
> upgpkg: pumba 0.11.6-1

- opkssh-bin/.SRCINFO
- opkssh-bin/PKGBUILD
> upgpkg: opkssh-bin 0.4.0-1

- opkssh/.SRCINFO
- opkssh/PKGBUILD
> upgpkg: opkssh 0.4.0-1

- cadvisor-bin/.SRCINFO
- cadvisor-bin/PKGBUILD
> upgpkg: cadvisor-bin 0.52.1-1

- opkssh/.SRCINFO
- opkssh/PKGBUILD
> upgpkg: opkssh 0.5.1-1

- opkssh-bin/.SRCINFO
- opkssh-bin/PKGBUILD
> upgpkg: opkssh-bin 0.5.1-1

- .github/workflows/schedule.yml
- ansible-core-git/.SRCINFO
- ansible-core-git/PKGBUILD
- ansible-core-git/relax_setuptools_version_requirements.patch
- **Add relax_setuptools_version_requirements.patch**
- **Revert "Disable ansible-core-git schedule"**
> Add relax_setuptools_version_requirements.patch

- opkssh-bin/.SRCINFO
- opkssh-bin/PKGBUILD
> upgpkg: opkssh-bin 0.6.0-1

- opkssh/.SRCINFO
- opkssh/PKGBUILD
> upgpkg: opkssh 0.6.0-1

- opkssh/.SRCINFO
- opkssh/PKGBUILD
> upgpkg: opkssh 0.7.0-1

- google-tsunami-security-scanner/.SRCINFO
- google-tsunami-security-scanner/PKGBUILD
> upgpkg: google-tsunami-security-scanner 0.1.0-1

- cadvisor-bin/.SRCINFO
- cadvisor-bin/PKGBUILD
upstream release
https://github.com/google/cadvisor/commit/1dd17f0
https://github.com/google/cadvisor/issues/3696
> upgpkg: cadvisor-bin 0.53.0-1

- opkssh/.SRCINFO
- opkssh/PKGBUILD
> upgpkg: opkssh 0.8.0-1

- .github/workflows/schedule.yml
- multi-git-status/.SRCINFO
- multi-git-status/PKGBUILD
- **Initial version of multi-git-status (2.0)**
- **Add license**
- **update multi-git-status to 2.1**
- **update to 2.2**
- **update .SRCINFO**
- **Add multi-git-status to schedule**
> add multi git status

- multi-git-status/.SRCINFO
- multi-git-status/PKGBUILD
- **Add aminvakil as maintainer**
- **upgpkg: multi-git-status 2.3-1**
- **Use sha256sums instead of md5sums**
> multi git status

- spotdl/.SRCINFO
- spotdl/PKGBUILD
> upgpkg: spotdl 4.4.1-1

- opkssh/.SRCINFO
- opkssh/PKGBUILD
> upgpkg: opkssh 0.9.0-1

- spotdl/.SRCINFO
- spotdl/PKGBUILD
> upgpkg: spotdl 4.4.2-1

- hadolint/.SRCINFO
- hadolint/PKGBUILD
- hadolint/stack.yaml
> upgpkg: hadolint 2.13.1-1

- hadolint/.SRCINFO
- hadolint/PKGBUILD
- hadolint/stack.yaml
> upgpkg: hadolint 2.14.0-1

- gnome-shell-extension-workspace-matrix/.SRCINFO
- gnome-shell-extension-workspace-matrix/PKGBUILD
> upgpkg: gnome-shell-extension-workspace-matrix 12.1-1

- butane-bin/.SRCINFO
- butane-bin/PKGBUILD
> upgpkg: butane-bin 0.25.1-1
